[package]
name = "cmp_flood_tide_xtask"
version = "0.1.0"
authors = ["aki <aki.akaguma@hotmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
flood-tide-gen = "0.1"
optstr-curl = { path="../../common/optstr-curl" }
update-file = { path="../../common/update-file" }
