use optstr_curl::parse_input_file;
use optstr_curl::OptStr;

pub fn do_gen_src() -> anyhow::Result<()> {
    let (vec_optstr, vec_line) = parse_input_file("comps/common/optstr-curl/src/curl.cmd.txt")?;
    //
    let sss = do_gen_src_help(&vec_optstr, &vec_line)?;
    update_file::update_file(&sss, "comps/cmp_pico_args/src/curl.cmd.help.rs.txt")?;
    //
    let sss = do_gen_src_match(&vec_optstr)?;
    update_file::update_file(&sss, "comps/cmp_pico_args/src/curl.cmd.match.rs.txt")?;
    //
    Ok(())
}

fn do_gen_src_help(vec_optstr: &[OptStr], vec_line: &[String]) -> anyhow::Result<String> {
    let mut sss = String::with_capacity(4 * 1024);
    //
    let s = r"// WARN: This file is auto generated by";
    sss += &format!("{} {}", s, env!("CARGO_PKG_NAME"));
    sss += r#"
const OPTIONS_TEXT: &str = r""#;
    for line in vec_line {
        sss += &format!("{}\n", line);
    }
    sss += "\";\n";
    //
    sss += r#"
#[derive(Debug, Default, PartialEq)]
pub struct CmdOptConf {
    pub opt_program: String,
    //
"#;
    for rec in vec_optstr.iter() {
        sss += &format!("    pub {}: {},\n", rec.field_s, rec.type_s);
    }
    sss += r#"    //
    pub arg_params: Vec<String>,
}
"#;
    //
    Ok(sss)
}

fn do_gen_src_match(vec_optstr: &[OptStr]) -> anyhow::Result<String> {
    let mut sss = String::with_capacity(4 * 1024);
    //
    let s = r"// WARN: This file is auto generated by";
    sss += &format!("{} {}", s, env!("CARGO_PKG_NAME"));
    //
    sss += r#"
{
"#;
    for rec in vec_optstr.iter() {
        let (key_s, sholon) = if !rec.sho.is_empty() && !rec.lon.is_empty() {
            (
                format!("[\"-{}\", \"--{}\"]", rec.sho, rec.lon),
                rec.lon.clone(),
            )
        } else if !rec.sho.is_empty() {
            (format!("\"-{}\"", rec.sho), rec.sho.clone())
        } else {
            (format!("\"--{}\"", rec.lon), rec.lon.clone())
        };
        match rec.type_s.as_str() {
            "bool" => match rec.field_s.as_str() {
                "flg_help" => {
                    sss += r#"
    if pico_args.contains(["-h", "--help"]) {
        print_help_and_exit(&conf);
    }
"#;
                }
                "flg_version" => {
                    sss += r#"
    if pico_args.contains(["-V", "--version"]) {
        print_version_and_exit(&conf);
    }
"#;
                }
                _ => {
                    sss += &format!(
                        "    conf.{} = pico_args.contains({});\n",
                        rec.field_s, key_s
                    );
                }
            },
            "String" => {
                sss += &format!(
                    concat!(
                        "    let x = pico_args.opt_value_from_str({});\n",
                        "    if let Ok(None) = x {{\n",
                        "        // noting todo\n",
                        "    }} else {{\n",
                        "        conf.{} = value_to_string(\"{}\", x)?\n",
                        "    }}\n",
                    ),
                    key_s, rec.field_s, sholon
                );
            }
            "u32" => {
                sss += &format!(
                    concat!(
                        "    let x = pico_args.opt_value_from_str({});\n",
                        "    if let Ok(None) = x {{\n",
                        "        // noting todo\n",
                        "    }} else {{\n",
                        "        conf.{} = value_to_u32(\"{}\", x)?\n",
                        "    }}\n",
                    ),
                    key_s, rec.field_s, sholon
                );
            }
            "u64" => {
                sss += &format!(
                    concat!(
                        "    let x = pico_args.opt_value_from_str({});\n",
                        "    if let Ok(None) = x {{\n",
                        "        // noting todo\n",
                        "    }} else {{\n",
                        "        conf.{} = value_to_u64(\"{}\", x)?\n",
                        "    }}\n",
                    ),
                    key_s, rec.field_s, sholon
                );
            }
            _ => unreachable!(),
        }
    }
    sss += r#"}
"#;
    //
    Ok(sss)
}
