[package]
name = "cmp_commander_xtask"
version = "0.1.0"
authors = ["Hidetoshi <hchacha@users.sourceforge.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
optstr-curl = { path="../../common/optstr-curl" }
update-file = { path="../../common/update-file" }
